export const WAITERS_GET_QUERY = "WAITERS_GET_QUERY";

export const WAITERS_MUTATION = "WAITERS_MUTATION";

export const WAITERS_ADD_QUERY = "WAITERS_ADD_QUERY";

export const DISHES_GET_QUERY = "DISHES_GET_QUERY";

export const DISHES_MUTATION = "DISHES_MUTATION";

export const DISHES_ADD_QUERY = "DISHES_ADD_QUERY";
