export const WAITERS_GET_QUERY = "WAITERS_GET_QUERY";

export const WAITERS_GET_ALL_QUERY = "WAITERS_GET_ALL_QUERY";

export const WAITERS_MUTATION = "WAITERS_MUTATION";

export const WAITERS_ADD_QUERY = "WAITERS_ADD_QUERY";

export const WAITERS_UPDATE_QUERY = "WAITERS_UPDATE_QUERY";

export const WAITERS_DELETE_QUERY = "WAITERS_DELETE_QUERY";

export const DISHES_GET_QUERY = "DISHES_GET_QUERY";

export const DISHES_MUTATION = "DISHES_MUTATION";

export const DISHES_ADD_QUERY = "DISHES_ADD_QUERY";

export const DISHES_UPDATE_QUERY = "DISHES_UPDATE_QUERY";

export const DISHES_DELETE_QUERY = "DISHES_DELETE_QUERY";

export const BILLS_MUTATION = "BILLS_MUTATION";

export const BILLS_CREATE_QUERY = "BILLS_CREATE_QUERY";

export const BILLS_UPDATE_QUERY = "BILLS_UPDATE_QUERY";

export const BILLS_DELETE_QUERY = "BILLS_DELETE_QUERY";

export const GOOGLE_PLACES_QUERY = "GOOGLE_PLACES_QUERY";
